# Generated by Django 4.2.30 on 2026-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.TextField(default='https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop')),
                ('pkg', models.CharField(max_length=200)),
                ('dates', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_country', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_notes', models.TextField(blank=True, null=True)),
                ('traveler_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('traveler_2_dob', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('destination', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('img', models.TextField()),
                ('tag', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('img', models.TextField()),
                ('accent', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('nights', models.IntegerField()),
                ('rating', models.FloatField(default=5.0)),
                ('reviews', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('priceWas', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('blurb', models.TextField()),
                ('img', models.TextField()),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('avatar', models.TextField()),
            ],
        ),
    ]
